name: Deploy Laravel to Production Server and Automate it

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Synchronize Files To FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/test.postocard.com/ # Adjust this to your FTP path


      # Optionally, if you need to run artisan commands remotely, you can keep this section:
      # - name: Run Remote Artisan Command
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.FTP_SERVER }}  # Adjust if needed
      #     username: ${{ secrets.FTP_USERNAME }}  # Adjust if needed
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}  # If you don't have SSH, you can remove this step
      #     script: |
      #       cd /path/on/ftp  # Adjust this to your FTP path
      #       php artisan migrate --force
      #       php artisan optimize
